modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="biome_waters"
version="${mod_version}"
displayName="Builders Companion Biome Waters"
description='''${mod_description}'''
authors="Judicius"

[[dependencies.biome_waters]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.biome_waters]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.biome_waters]]
modId="bc_core"
mandatory=true
versionRange="[1.20.1-1.0.0,)"
ordering="AFTER"
side="BOTH"
