modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="bc_core"
version="${mod_version}"
displayName="Builders Companion Core"
description='''Core framework for Builders Companion mods'''
authors="Judicius"

[[dependencies.bc_core]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.bc_core]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"